spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vectors
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql